name: Exam-portal

on:
  push:
    branches:
      - main  # Triggers the live deployment whenever you push to main

jobs:
 deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Pull the code from your GitHub repo onto the runner
     - name: Checkout Code
       uses: actions/checkout@v4

      # 2. Log in to AWS using your GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Ensure this matches your S3 bucket region

      # 3. Sync files to S3 (Excluding GitHub-specific hidden folders)
      - name: Deploy to S3
        run: |
          aws s3 sync . s3://examportal-jancol --delete --exclude ".git/*" --exclude ".github/*"

      # 4. Refresh the CloudFront CDN so the changes show up immediately
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths "/*"
